# Generated by Django 3.1.2 on 2020-11-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='mobile',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
