# Generated by Django 3.1.2 on 2020-11-18 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201110_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='suspend',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SuspendedAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
