# Generated by Django 3.0.3 on 2020-04-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200327_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='esignature',
            field=models.FileField(blank=True, null=True, upload_to='esignature'),
        ),
    ]
