# Generated by Django 3.1.2 on 2020-10-28 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('business_name', models.CharField(blank=True, max_length=400, null=True)),
                ('investor_id', models.CharField(default='', max_length=125)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss.', 'Miss.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Rev.', 'Rev.')], max_length=20)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=400)),
                ('state', models.CharField(max_length=400)),
                ('working_status', models.CharField(choices=[('Employee', 'Employee'), ('Government Employee', 'Government Employee'), ('Private Sector Employee', 'Private Sector Employee'), ('Owner', 'Owner'), ('Student', 'Student'), ('Overseas Worker', 'Overseas Worker'), ('Pensioner', 'Pensioner'), ('Unemployed', 'Unemployed')], max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='investor')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investor')),
            ],
        ),
        migrations.CreateModel(
            name='LoanInvestmentProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('interest_rate_per_annum', models.DecimalField(decimal_places=2, max_digits=6)),
                ('interest_duration', models.CharField(choices=[('Per Day', 'Per Day'), ('Per Week', 'Per Week'), ('Per Month', 'Per Month'), ('Per Year', 'Per Year')], max_length=100)),
                ('interest_posting_frequency', models.CharField(choices=[('Every 1 month', 'Every 1 month'), ('Every 2 month', 'Every 2 month'), ('Every 3 month', 'Every 3 month'), ('Every 4 month', 'Every 4 month'), ('Every 6 month', 'Every 6 month'), ('Every 12 month', 'Every 12 month')], max_length=200)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
            ],
        ),
        migrations.CreateModel(
            name='LoanInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.loan')),
                ('loan_investment_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.loaninvestmentproduct')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Interest', 'Interest'), ('Dividend', 'Dividend'), ('Transfer In', 'Transfer In'), ('Withdrawal', 'Withdrawal'), ('Bank Fees', 'Bank Fees'), ('Transfer Out', 'Transfer Out'), ('Commission', 'Commission')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
                ('investor_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investoraccount')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('interest_rate_per_annum', models.DecimalField(decimal_places=2, max_digits=6)),
                ('interest_posting_frequency', models.CharField(choices=[('Every 1 month', 'Every 1 month'), ('Every 2 month', 'Every 2 month'), ('Every 3 month', 'Every 3 month'), ('Every 4 month', 'Every 4 month'), ('Every 6 month', 'Every 6 month'), ('Every 12 month', 'Every 12 month')], max_length=200)),
                ('min_balance_for_interest_rate', models.DecimalField(decimal_places=2, max_digits=100)),
                ('allow_overdraw', models.BooleanField(default=False)),
                ('min_balance_for_withdrawal', models.DecimalField(decimal_places=2, max_digits=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investors.investor')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='investor_documents')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investor')),
            ],
        ),
        migrations.AddField(
            model_name='investoraccount',
            name='investor_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investorproduct'),
        ),
    ]
