# Generated by Django 3.0.3 on 2020-04-29 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_branch_capital'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=400, null=True)),
                ('investor_id', models.CharField(default='', max_length=125)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('investor_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investors.InvestorAccount')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='investor_documents')),
                ('investor_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.InvestorAccount')),
            ],
        ),
    ]
