# Generated by Django 3.0.3 on 2020-05-05 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0015_loanrepayment_branch'),
        ('accounts', '0002_branch_capital'),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investoraccount',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='investoraccount',
            name='investor_id',
        ),
        migrations.RemoveField(
            model_name='investoraccount',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='investordocuments',
            name='investor_account',
        ),
        migrations.RemoveField(
            model_name='investorinvitation',
            name='investor_account',
        ),
        migrations.AddField(
            model_name='investoraccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='investoraccount',
            name='investor_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='LoanInvestmentProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('interest_rate_per_annum', models.DecimalField(decimal_places=2, max_digits=6)),
                ('interest_duration', models.CharField(choices=[('Per Day', 'Per Day'), ('Per Week', 'Per Week'), ('Per Month', 'Per Month'), ('Per Year', 'Per Year')], max_length=100)),
                ('interest_posting_frequency', models.CharField(choices=[('Every 1 month', 'Every 1 month'), ('Every 2 month', 'Every 2 month'), ('Every 3 month', 'Every 3 month'), ('Every 4 month', 'Every 4 month'), ('Every 6 month', 'Every 6 month'), ('Every 12 month', 'Every 12 month')], max_length=200)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='LoanInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.Loan')),
                ('loan_investment_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.LoanInvestmentProduct')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Interest', 'Interest'), ('Dividend', 'Dividend'), ('Transfer In', 'Transfer In'), ('Withdrawal', 'Withdrawal'), ('Bank Fees', 'Bank Fees'), ('Transfer Out', 'Transfer Out'), ('Commission', 'Commission')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('investor_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.InvestorAccount')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('interest_rate_per_annum', models.DecimalField(decimal_places=2, max_digits=6)),
                ('interest_posting_frequency', models.CharField(choices=[('Every 1 month', 'Every 1 month'), ('Every 2 month', 'Every 2 month'), ('Every 3 month', 'Every 3 month'), ('Every 4 month', 'Every 4 month'), ('Every 6 month', 'Every 6 month'), ('Every 12 month', 'Every 12 month')], max_length=200)),
                ('min_balance_for_interest_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('allow_overdraw', models.BooleanField(default=False)),
                ('min_balance_for_withdrawal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=400, null=True)),
                ('investor_id', models.CharField(default='', max_length=125)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='investoraccount',
            name='investor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='investors.Investor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investoraccount',
            name='investor_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='investors.InvestorProduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investordocuments',
            name='investor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='investors.Investor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investorinvitation',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investors.Investor'),
        ),
    ]
