# Generated by Django 3.1.2 on 2020-11-20 09:51

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201118_1500'),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(default='', max_length=255)),
                ('sent', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='investor',
            name='profile',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='investordocuments',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
    ]
