# Generated by Django 3.0.3 on 2020-05-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_auto_20200505_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='profile',
        ),
        migrations.AddField(
            model_name='investor',
            name='address',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='city',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='email',
            field=models.EmailField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='middle_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='mobile',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='investor'),
        ),
        migrations.AddField(
            model_name='investor',
            name='state',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss.', 'Miss.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Rev.', 'Rev.')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='working_status',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Government Employee', 'Government Employee'), ('Private Sector Employee', 'Private Sector Employee'), ('Owner', 'Owner'), ('Student', 'Student'), ('Overseas Worker', 'Overseas Worker'), ('Pensioner', 'Pensioner'), ('Unemployed', 'Unemployed')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
