# Generated by Django 3.0.3 on 2020-05-07 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branch_capital'),
        ('investors', '0003_auto_20200506_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaninvestmentproduct',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Branch'),
        ),
    ]
