# Generated by Django 3.0.3 on 2020-05-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0004_auto_20200507_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorproduct',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='investorproduct',
            name='min_balance_for_interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='investorproduct',
            name='min_balance_for_withdrawal',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
