# Generated by Django 3.0.3 on 2020-05-07 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branch_capital'),
        ('investors', '0005_auto_20200507_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='investortransaction',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Branch'),
            preserve_default=False,
        ),
    ]
