# Generated by Django 3.0.3 on 2020-04-29 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0015_loanrepayment_branch'),
        ('borrowers', '0003_auto_20200420_1821'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_loan_released', models.PositiveIntegerField(default=0)),
                ('principal_released', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('due_loans_pricipal', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('due_loans_interest', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('due_loans_fees', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('due_loans_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('due_loans_total', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('payments_principal', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('payments_interest', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('payments_fees', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('payment_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('payments_total', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanBorrowerReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_loan_released', models.PositiveIntegerField(default=0)),
                ('principal_released', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('due_loans_pricipal', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('due_loans_interest', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('due_loans_fees', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('due_loans_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('due_loans_total', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('payments_principal', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('payments_interest', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('payments_fees', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('payment_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('payments_total', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowers.Borrower')),
            ],
        ),
    ]
