# Generated by Django 3.0.3 on 2020-04-01 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200326_0729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarlog',
            options={'get_latest_by': ['-date']},
        ),
        migrations.RenameField(
            model_name='calendarevent',
            old_name='when_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='calendarevent',
            old_name='from_date',
            new_name='till_date',
        ),
    ]
