# Generated by Django 3.0 on 2020-05-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_loanborrowerreport_loanreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanborrowerreport',
            name='due_loans_pricipal',
        ),
        migrations.RemoveField(
            model_name='loanborrowerreport',
            name='payment_penalty',
        ),
        migrations.AddField(
            model_name='loanborrowerreport',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loanborrowerreport',
            name='due_loans_principal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='loanborrowerreport',
            name='payments_penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='loanborrowerreport',
            name='principal_at_risk',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
