# Generated by Django 3.0 on 2020-05-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200506_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanborrowerreport',
            name='no_loan_released',
        ),
    ]
