# Generated by Django 3.0 on 2020-05-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_loanborrowerreport_no_loan_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanborrowerreport',
            name='loan_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
