# Generated by Django 3.1.2 on 2020-11-06 16:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSafeManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
            ],
        ),
        migrations.CreateModel(
            name='CashSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cash_safe_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings_investments.cashsafemanagement')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings_id', models.CharField(blank=True, max_length=125, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('available_balance', models.DecimalField(decimal_places=2, max_digits=100)),
                ('ledger_balance', models.DecimalField(decimal_places=2, max_digits=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('commission_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Interest', 'Interest'), ('Dividend', 'Dividend'), ('Transfer In', 'Transfer In'), ('Withdrawal', 'Withdrawal'), ('Bank Fees', 'Bank Fees'), ('Transfer Out', 'Transfer Out'), ('Commission', 'Commission')], max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('total_balance', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('report_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('report_transfer_in', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('report_withdrawal', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('report_fees', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('report_interest', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('report_dividend', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('report_transfer_out', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('report_commission', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('report_balance', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('cash_safe_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings_investments.cashsafemanagement')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TransferCash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('cash_safe_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings_investments.cashsafemanagement')),
                ('from_cash_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_cash_source', to='savings_investments.cashsource')),
                ('from_teller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_teller', to='savings_investments.teller')),
                ('to_cash_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_cash_source', to='savings_investments.cashsource')),
                ('to_teller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_teller', to='savings_investments.teller')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Bank Fee', 'Bank Fee'), ('Interest', 'Interest'), ('Dividend', 'Dividend'), ('Transfer In', 'Transfer In'), ('Transfer Out', 'Transfer Out'), ('Commission', 'Commission')], max_length=100)),
                ('date_time', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('account_to_account_transfer', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
                ('savings_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings_investments.savingsaccount')),
                ('teller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='savings_investments.teller')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('interest_rate_per_annum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_method', models.CharField(choices=[('Last Savings Balance', 'Last Savings Balance'), ('Pro-Rata Basis', 'Pro-Rata Basis')], max_length=100)),
                ('interest_posting_frequency', models.CharField(choices=[('Every 1 Month', 'Every 1 Month'), ('Every 2 Month', 'Every 2 Month'), ('Every 3 Month', 'Every 3 Month'), ('Every 4 Month', 'Every 4 Month'), ('Every 6 Month', 'Every 6 Month'), ('Every 12 Month', 'Every 12 Month')], max_length=300)),
                ('min_balance_for_interest', models.DecimalField(decimal_places=2, max_digits=100)),
                ('overdrawn', models.BooleanField(default=False)),
                ('min_balance_for_withdrawal', models.DecimalField(decimal_places=2, max_digits=100)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('transfer_in', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('withdrawal', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('dividend', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('transfer_out', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('fee_posting_frequency', models.CharField(choices=[('Every 1 month', 'Every 1 month'), ('Every 2 month', 'Every 2 month'), ('Every 3 month', 'Every 3 month'), ('Every 4 month', 'Every 4 month'), ('Every 6 month', 'Every 6 month'), ('Every 12 month', 'Every 12 month'), ('One-time', 'One-time')], max_length=200)),
                ('first_fee', models.CharField(choices=[('Full Fee Amount', 'Full Fee Amount'), ('Pro-Rata Basis', 'Pro-Rata Basis')], max_length=200)),
                ('savings_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings_investments.savingsproduct')),
            ],
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='savings_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings_investments.savingsproduct'),
        ),
        migrations.CreateModel(
            name='FundTransferLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('date_time', models.DateTimeField()),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_account', to='savings_investments.savingsaccount')),
                ('teller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='savings_investments.teller')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_account', to='savings_investments.savingsaccount')),
            ],
        ),
        migrations.CreateModel(
            name='CustomSavingsAccountField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=125)),
                ('text_field', models.TextField(blank=True, null=True)),
                ('date_field', models.DateField(blank=True, null=True)),
                ('integer_field', models.PositiveIntegerField(blank=True, null=True)),
                ('decimal_field', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('url_field', models.URLField(blank=True, max_length=500, null=True)),
                ('text_area', models.TextField(blank=True, null=True)),
                ('dropdown_values', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('dropdown', models.CharField(blank=True, max_length=200, null=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='savings_accounts')),
                ('savings_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings_investments.savingsaccount')),
            ],
        ),
    ]
