# Generated by Django 3.0.3 on 2020-03-25 05:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20200324_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('interest_rate_per_anum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_method', models.CharField(choices=[('Last Savings Balance', 'Last Savings Balance'), ('Pro-Rata Basis', 'Pro-Rata Basis')], max_length=100)),
                ('interest_posting_frequency', models.CharField(blank=True, max_length=300, null=True)),
                ('interest_addition_time', models.CharField(blank=True, max_length=300, null=True)),
                ('min_balance_for_interest', models.DecimalField(decimal_places=2, max_digits=100)),
                ('overdrawn', models.BooleanField(default=False)),
                ('min_balance_for_withdrawal', models.DecimalField(decimal_places=2, max_digits=100)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings_id', models.CharField(blank=True, max_length=125, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('available_balance', models.DecimalField(decimal_places=2, max_digits=100)),
                ('ledger_balance', models.DecimalField(decimal_places=2, max_digits=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Branch')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('savings_product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='savings_investments.SavingsProduct')),
            ],
        ),
        migrations.CreateModel(
            name='CustomSavingsAccountField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=125)),
                ('text_field', models.TextField(blank=True, null=True)),
                ('date_field', models.DateField(blank=True, null=True)),
                ('integer_field', models.PositiveIntegerField(blank=True, null=True)),
                ('decimal_field', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('url_field', models.URLField(blank=True, max_length=500, null=True)),
                ('text_area', models.TextField(blank=True, null=True)),
                ('dropdown_values', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('dropdown', models.CharField(blank=True, max_length=200, null=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='savings_accounts')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings_investments.SavingsAccount')),
            ],
        ),
    ]
