# Generated by Django 3.0.3 on 2020-04-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings_investments', '0002_auto_20200410_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsproduct',
            name='interest_addition_time',
        ),
        migrations.AlterField(
            model_name='savingsproduct',
            name='interest_posting_frequency',
            field=models.CharField(choices=[('Every 1 Month', 'Every 1 Month'), ('Every 2 Month', 'Every 2 Month'), ('Every 3 Month', 'Every 3 Month'), ('Every 4 Month', 'Every 4 Month'), ('Every 6 Month', 'Every 6 Month'), ('Every 12 Month', 'Every 12 Month')], default='', max_length=300),
            preserve_default=False,
        ),
    ]
