# Generated by Django 3.0.3 on 2020-04-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings_investments', '0003_auto_20200410_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsaccount',
            name='savings_id',
            field=models.CharField(blank=True, max_length=125, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teller',
            name='credit_coins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='teller',
            name='credit_notes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='teller',
            name='debit_coins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='teller',
            name='debit_notes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='teller',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
