# Generated by Django 3.0.3 on 2020-04-13 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('savings_investments', '0004_auto_20200413_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teller',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
