# Generated by Django 3.0.3 on 2020-04-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings_investments', '0005_auto_20200413_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingstransaction',
            name='amount',
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='amount_coins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='amount_notes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
