# Generated by Django 3.0.3 on 2020-04-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings_investments', '0006_auto_20200413_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashsource',
            old_name='bank_balance_cash',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='savingstransaction',
            old_name='amount_coins',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='teller',
            old_name='credit_coins',
            new_name='credit',
        ),
        migrations.RenameField(
            model_name='teller',
            old_name='credit_notes',
            new_name='debit',
        ),
        migrations.RenameField(
            model_name='transfercash',
            old_name='amount_coins',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='cashsource',
            name='bank_balance_coins',
        ),
        migrations.RemoveField(
            model_name='cashsource',
            name='total_balance',
        ),
        migrations.RemoveField(
            model_name='savingstransaction',
            name='amount_notes',
        ),
        migrations.RemoveField(
            model_name='teller',
            name='debit_coins',
        ),
        migrations.RemoveField(
            model_name='teller',
            name='debit_notes',
        ),
        migrations.RemoveField(
            model_name='transfercash',
            name='amount_notes',
        ),
    ]
