# Generated by Django 3.0.3 on 2020-04-14 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings_investments', '0007_auto_20200413_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfercash',
            name='from_teller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_teller', to='savings_investments.Teller'),
        ),
        migrations.AlterField(
            model_name='transfercash',
            name='to_teller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_teller', to='savings_investments.Teller'),
        ),
    ]
