# Generated by Django 3.0.3 on 2020-04-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings_investments', '0008_auto_20200414_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashsource',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='cashsource',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
