# Generated by Django 3.0.3 on 2020-04-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings_investments', '0009_auto_20200414_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsproduct',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='savingsproduct',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='savingsproduct',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='savingsproduct',
            name='dividend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='savingsproduct',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='savingsproduct',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='savingsproduct',
            name='transfer_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='savingsproduct',
            name='transfer_out',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='savingsproduct',
            name='withdrawal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
