# Generated by Django 3.0.3 on 2020-04-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings_investments', '0010_auto_20200415_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingstransaction',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
