# Generated by Django 3.0.3 on 2020-04-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings_investments', '0011_savingstransaction_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='teller',
            name='report_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='teller',
            name='report_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='teller',
            name='report_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='teller',
            name='report_dividend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='teller',
            name='report_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='teller',
            name='report_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='teller',
            name='report_transfer_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='teller',
            name='report_transfer_out',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='teller',
            name='report_withdrawal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
