# Generated by Django 3.0.3 on 2020-04-15 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings_investments', '0012_auto_20200415_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingstransaction',
            name='teller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='savings_investments.Teller'),
        ),
        migrations.CreateModel(
            name='FundTransferLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('date_time', models.DateTimeField()),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_account', to='savings_investments.SavingsAccount')),
                ('teller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='savings_investments.Teller')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_account', to='savings_investments.SavingsAccount')),
            ],
        ),
    ]
