# Generated by Django 3.0.3 on 2020-05-11 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings_investments', '0015_auto_20200427_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('fee_posting_frequency', models.CharField(choices=[('Every 1 month', 'Every 1 month'), ('Every 2 month', 'Every 2 month'), ('Every 3 month', 'Every 3 month'), ('Every 4 month', 'Every 4 month'), ('Every 6 month', 'Every 6 month'), ('Every 12 month', 'Every 12 month'), ('One-time', 'One-time')], max_length=200)),
                ('first_fee', models.CharField(choices=[('Full Fee Amount', 'Full Fee Amount'), ('Pro-Rata Basis', 'Pro-Rata Basis')], max_length=200)),
                ('savings_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings_investments.SavingsProduct')),
            ],
        ),
    ]
