# Generated by Django 3.0.3 on 2020-03-24 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('disbursement_mode', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Wire Transfer', 'Wire Transfer'), ('Online Transfer', 'Online Transfer')], max_length=100)),
                ('duration', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('settled', 'settled'), ('disbursed', 'disbursed'), ('canceled', 'canceled')], default='pending', max_length=30)),
                ('request_date', models.DateField(auto_now=True)),
                ('loan_release_date', models.DateField(blank=True, null=True)),
                ('direct_debit', models.BooleanField(default=False)),
                ('interest_type', models.CharField(choices=[('Percentage Based', 'Percentage Based'), ('Fixed Amount Per Cycle', 'Fixed Amount Per Cycle')], max_length=100)),
                ('loan_interest_percentage', models.CharField(blank=True, max_length=400, null=True)),
                ('loan_interest_fixed_amount', models.CharField(blank=True, max_length=400, null=True)),
                ('loan_interest_percentage_period', models.CharField(blank=True, choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months'), ('Years', 'Years')], max_length=400, null=True)),
                ('loan_duration', models.CharField(blank=True, max_length=400, null=True)),
                ('loan_duration_period', models.CharField(blank=True, choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months'), ('Years', 'Years')], max_length=400, null=True)),
                ('number_of_repayments', models.PositiveIntegerField(default=1)),
                ('decimal_places', models.CharField(blank=True, choices=[('round_off_2dp', 'round_off_2dp'), ('round_off_Integer', 'round_off_Integer'), ('round_off_1_dp', 'round_off_1_dp'), ('round_up_1dp', 'round_up_1dp'), ('round_up_10', 'round_up_10'), ('round_off_100', 'round_off_100')], max_length=400, null=True)),
                ('interest_start_date', models.DateField(blank=True, null=True)),
                ('first_repayment_date', models.DateField(blank=True, null=True)),
                ('last_repayment_date', models.DateField(blank=True, null=True)),
                ('first_repayment_on_prorata', models.BooleanField(default=False)),
                ('adjust_remaining_repayments', models.BooleanField(default=False)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('repayment_amount', models.CharField(blank=True, max_length=400, null=True)),
                ('amount_paid', models.CharField(blank=True, max_length=400, null=True)),
                ('remaining_balance', models.CharField(blank=True, max_length=400, null=True)),
                ('interest_on_prorata', models.BooleanField(default=False)),
                ('loan_score', models.PositiveIntegerField(blank=True, null=True)),
                ('penalty_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('staff_permission_disbursed', models.BooleanField(default=True)),
                ('staff_permission_accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LoanOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=128, null=True)),
                ('loan', models.ManyToManyField(to='loans.Loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(choices=[('Business', 'Business'), ('Overseas', 'Overseas'), ('Pensioner', 'Pensioner'), ('Personal', 'Personal'), ('Student', 'Student')], max_length=100)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LoanScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('settled', 'settled'), ('overdue', 'overdue')], max_length=30)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.Loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=60)),
                ('date', models.DateField()),
                ('payment_type', models.CharField(blank=True, choices=[('manual', 'manual'), ('card', 'card')], max_length=128, null=True)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending'), ('declined', 'declined')], max_length=60)),
                ('charge_interest', models.CharField(choices=[('normally', 'normally'), ('charge_on_release_date', 'charge_on_release_date'), ('charge_on_first_repayment', 'charge_on_first_repayment'), ('charge_on_last_repayment', 'charge_on_last_repayment'), ('do_not_charge_on_last_repayment', 'do_not_charge_on_last_repayment')], max_length=60)),
                ('repayment_cycle', models.CharField(blank=True, choices=[('daily', 'daily'), ('weekly', 'weekly'), ('biweekly', 'biweekly'), ('monthly', 'monthly'), ('bi-monthly', 'bi-monthly'), ('quarterly', 'quarterly'), ('every 4 months', 'every 4 months'), ('semi-annually', 'semi-annually'), ('annually', 'annually'), ('lump sum', 'lump sum')], max_length=400, null=True)),
                ('loan_schedule', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.LoanScheduler')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRemainder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before_due', models.PositiveIntegerField(default=1)),
                ('frequency', models.PositiveIntegerField(default=1)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.Loan')),
                ('staff_to_receive_remainder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.LoanOfficer')),
            ],
        ),
        migrations.CreateModel(
            name='LoanGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.Loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('interest_type', models.CharField(choices=[('Percentage Based', 'Percentage Based'), ('Fixed Amount Per Cycle', 'Fixed Amount Per Cycle')], max_length=100)),
                ('apply_loan_fee', models.CharField(choices=[('Principal', 'Principal'), ('Interest', 'Interest'), ('Principal + Interest', 'Principal + Interest')], max_length=100)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.Loan')),
                ('staff_initiating_it', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.LoanOfficer')),
            ],
        ),
        migrations.CreateModel(
            name='LoanDisbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.Loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.Loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanCollateral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('type1', 'type1'), ('type2', 'type2'), ('type3', 'type3')], max_length=100)),
                ('name', models.CharField(max_length=400)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('register_date', models.DateField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.Loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.Loan')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.LoanType'),
        ),
    ]
