# Generated by Django 3.0.3 on 2020-04-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount_paid',
            field=models.IntegerField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='remaining_balance',
            field=models.IntegerField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='repayment_amount',
            field=models.IntegerField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='loanofficer',
            name='loan',
            field=models.ManyToManyField(blank=True, null=True, to='loans.Loan'),
        ),
    ]
