# Generated by Django 3.0.3 on 2020-03-24 13:50

from django.db import migrations, models
import loans.models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='repayments', validators=[loans.models.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='repayment_mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Wire Transfer', 'Wire Transfer'), ('Online Transfer', 'Online Transfer'), ('PayPal', 'PayPal')], max_length=400, null=True),
        ),
    ]
