# Generated by Django 3.1.2 on 2020-11-04 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanfee',
            name='percentage',
        ),
    ]
