# Generated by Django 3.0.3 on 2020-04-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20200408_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='maturity',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='released',
        ),
        migrations.AlterField(
            model_name='loan',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
