# Generated by Django 3.1.2 on 2020-11-06 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('loans', '0002_remove_loanguarantor_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanguarantor',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='loanguarantor',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.country'),
        ),
    ]
