# Generated by Django 3.1.2 on 2020-11-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_remove_loanfee_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanfee',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
