# Generated by Django 3.0.3 on 2020-03-25 05:12

from django.db import migrations, models
import django.db.models.deletion
import loans.models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20200324_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanCollateralTypes',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(choices=[('Automobiles', 'Automobiles'), ('Electronic Items', 'Electronic Items'), ('Insurance Policies', 'Insurance Policies'), ('Investments', 'Investments'), (
                    'Machineries and Equipments', 'Machineries and Equipments'), ('Real Estate', 'Real Estate'), ('Valuables and Collectibles', 'Valuables and Collectibles')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Wire Transfer', 'Wire Transfer'), (
                    'Online Transfer', 'Online Transfer'), ('PayPal', 'PayPal')], max_length=400, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='adjust_remaining_repayments',
            new_name='maturity',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='first_repayment_on_prorata',
            new_name='released',
        ),
        migrations.RenameField(
            model_name='loancollateral',
            old_name='amount',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='disbursement_mode',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='first_repayment_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='last_repayment_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='number_of_repayments',
        ),
        migrations.RemoveField(
            model_name='loancollateral',
            name='loan_type',
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='collateral_files',
            field=models.FileField(blank=True, null=True, upload_to='repayments', validators=[
                                   loans.models.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='collateral_photo',
            field=models.FileField(blank=True, null=True, upload_to='repayments', validators=[
                                   loans.models.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='colour',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='current_status',
            field=models.CharField(choices=[('Deposited into branch', 'Deposited into branch'), ('Collateral with borrower', 'Collateral with borrower'), ('Returned to borrower', 'Returned to borrowerI'), (
                'Repossession initiated', 'Repossession initiated'), ('under auction', 'under auction'), ('sold', 'sold'), ('lost', 'lost')], default='sold', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='date_of_manufacturer',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='engine_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='item_state',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), (
                'Fair', 'Fair'), ('Damaged', 'Damaged')], default='Good', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='last_updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='mileage',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='model_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='model_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='reg_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='serial_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='loancomment',
            name='author',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='loans.LoanOfficer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loandisbursement',
            name='disbursement_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Wire Transfer', 'Wire Transfer'), (
                'Online Transfer', 'Online Transfer')], default='Cash', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='adjust_remaining_repayments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='amortization',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='collector',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='loans.LoanOfficer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='days_passed',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='first_repayment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='first_repayment_on_prorata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='grace_period',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='grace_period_once_per_loan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='last_repayment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='number_of_repayments',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='penalty_branch_holiday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='pending_due',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='loantype',
            name='apply_penaly_to',
            field=models.CharField(choices=[('Fully Paid Loans', 'Fully Paid Loans'), ('Defaulted Loans', (('Credit Counseling Loans', 'Credit Counseling Loans'), ('Collection Agency Loans', 'Collection Agency Loans'), (
                'Sequestrate Loans', 'Sequestrate Loans'), ('Debt Review Loans', 'Debt Review Loans'), ('Fraud Loans', 'Fraud Loans'), ('Legal Loans', 'Legal Loans'), ('Write-Off Loans', 'Write-Off Loans')))], default='Fully Paid Loans', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('open', (('current', 'current'), ('due today', 'due today'), ('missed repayment', 'missed repayment'), ('arrears', 'arrears'), ('past maturity', 'past maturity'))), ('restructured', 'restructured'), ('fully paid', 'fully paid'), ('defaulted', ((
                'credit counselling', 'credit counselling'), ('collection agency', 'collection agency'), ('sequestrate', 'sequestrate'), ('debt review', 'debt review'), ('fraud', 'fraud'), ('investigation', 'investigation'), ('legal', 'legal'), ('write-off', 'write-off'))), ('denied', 'denied'), ('not taken up', 'not taken up')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='collateral_type',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='loans.LoanCollateralTypes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='repayment_mode',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='loans.LoanRepaymentMethod'),
            preserve_default=False,
        ),
    ]
