# Generated by Django 3.0.3 on 2020-03-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_auto_20200325_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancollateraltypes',
            name='division',
            field=models.CharField(choices=[('Automobiles', 'Automobiles'), ('Electronic Items', 'Electronic Items'), ('Insurance Policies', 'Insurance Policies'), ('Investments', 'Investments'), ('Machineries and Equipments', 'Machineries and Equipments'), ('Real Estate', 'Real Estate'), ('Valuables and Collectibles', 'Valuables and Collectibles'), ('Others', 'Others')], max_length=100),
        ),
    ]
