# Generated by Django 3.0.3 on 2020-04-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_auto_20200408_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount_paid',
            field=models.IntegerField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='remaining_balance',
            field=models.IntegerField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='repayment_amount',
            field=models.IntegerField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
