# Generated by Django 3.1.2 on 2020-11-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanfee_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanofficer',
            name='members',
        ),
    ]
