# Generated by Django 3.1.2 on 2020-11-06 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_remove_loanguarantor_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanguarantor',
            name='branch',
        ),
    ]
