# Generated by Django 3.0.3 on 2020-03-25 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200324_1113'),
        ('loans', '0005_loan_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Branch'),
            preserve_default=False,
        ),
    ]
