# Generated by Django 3.1.2 on 2020-11-06 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_remove_loanguarantor_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanguarantor',
            name='borrower',
        ),
    ]
