# Generated by Django 3.0.3 on 2020-04-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_auto_20200409_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='repayment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
