# Generated by Django 3.0.3 on 2020-04-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loan_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepayment',
            name='repayment_mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Wire Transfer', 'Wire Transfer'), ('Online Transfer', 'Online Transfer'), ('PayPal', 'PayPal')], max_length=400, null=True),
        ),
        migrations.DeleteModel(
            name='LoanRepaymentMethod',
        ),
    ]
