# Generated by Django 3.0.3 on 2020-04-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_auto_20200409_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='comment',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
