# Generated by Django 3.1.2 on 2020-11-06 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('borrowers', '0002_auto_20201106_2219'),
        ('loans', '0006_remove_loanguarantor_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanguarantor',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='borrowers.borrower'),
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.country'),
        ),
    ]
