# Generated by Django 3.1.2 on 2020-11-06 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
        ('loans', '0007_auto_20201106_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanofficer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='loanofficer',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='loanofficer',
            name='staff_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.staff'),
        ),
    ]
