# Generated by Django 3.0.3 on 2020-04-09 21:40

from django.db import migrations, models
import loans.models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_auto_20200409_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepayment',
            name='proof_of_payment',
            field=models.FileField(upload_to='repayments', validators=[loans.models.validate_file_extension]),
        ),
    ]
