# Generated by Django 3.0.3 on 2020-04-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_auto_20200403_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='last_activity_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
