# Generated by Django 3.0.3 on 2020-04-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_auto_20200409_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepayment',
            name='days_passed',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='number_of_repayments',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
