# Generated by Django 3.0.3 on 2020-04-06 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_auto_20200406_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancollateral',
            name='current_status',
            field=models.CharField(choices=[('Deposited into branch', 'Deposited into branch'), ('Collateral with borrower', 'Collateral with borrower'), ('Returned to borrower', 'Returned to borrower'), ('Repossession initiated', 'Repossession initiated'), ('under auction', 'under auction'), ('sold', 'sold'), ('lost', 'lost')], max_length=100),
        ),
        migrations.CreateModel(
            name='LoanGuarantor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('business_name', models.CharField(blank=True, max_length=400, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200)),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Rev.', 'Rev.')], max_length=5)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=400)),
                ('state', models.CharField(max_length=400)),
                ('zip_code', models.CharField(max_length=400)),
                ('landline_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('working_status', models.CharField(choices=[('Employee', 'Employee'), ('Government Employee', 'Government Employee'), ('Private Sector Employee', 'Private Sector Employee'), ('Owner', 'Owner'), ('Student', 'Student'), ('Overseas Worker', 'Overseas Worker'), ('Pensioner', 'Pensioner'), ('Unemployed', 'Unemployed')], max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='guarantor')),
                ('description', models.TextField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Loan')),
            ],
        ),
        migrations.CreateModel(
            name='GuarantorFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='guarantor_files')),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.LoanGuarantor')),
            ],
        ),
    ]
