# Generated by Django 3.0.3 on 2020-04-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_loan_last_activity_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='last_activity_date',
        ),
        migrations.AlterField(
            model_name='loancollateral',
            name='collateral_type',
            field=models.CharField(choices=[('Automobiles', 'Automobiles'), ('Electronic Items', 'Electronic Items'), ('Insurance Policies', 'Insurance Policies'), ('Investments', 'Investments'), ('Machineries and Equipments', 'Machineries and Equipments'), ('Real Estate', 'Real Estate'), ('Valuables and Collectibles', 'Valuables and Collectibles'), ('Others', 'Others')], max_length=100),
        ),
        migrations.DeleteModel(
            name='LoanCollateralTypes',
        ),
    ]
