# Generated by Django 3.1.2 on 2020-11-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_remove_loan_loan_guarantor'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_guarantor',
            field=models.ManyToManyField(blank=True, default='', related_name='loan_guarantor', to='loans.LoanGuarantor'),
        ),
    ]
