# Generated by Django 3.0.3 on 2020-04-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_auto_20200406_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanguarantor',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
