# Generated by Django 3.1.2 on 2020-11-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_loan_loan_guarantor'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_on', models.DateField(auto_now_add=True)),
                ('loan', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='loans.loan')),
                ('loan_officer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='loans.loanofficer')),
            ],
        ),
    ]
