# Generated by Django 3.0.3 on 2020-04-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_auto_20200407_0621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoanAttachments',
            new_name='LoanAttachment',
        ),
    ]
