# Generated by Django 3.0.3 on 2020-04-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_auto_20200406_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='loan_score',
        ),
        migrations.AddField(
            model_name='loan',
            name='bvn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
