# Generated by Django 3.1.2 on 2020-11-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_officerloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='no_of_repayments',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
