# Generated by Django 3.0.3 on 2020-04-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_loan_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
