# Generated by Django 3.1.2 on 2020-11-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_loan_no_of_repayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanscheduler',
            name='principal_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
