# Generated by Django 3.0.3 on 2020-04-10 21:43

from django.db import migrations, models
import loans.models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_loan_authorization_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepayment',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='repayments', validators=[loans.models.validate_file_extension]),
        ),
    ]
