# Generated by Django 3.1.2 on 2020-11-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0014_auto_20201111_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='amount_taken',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
