# Generated by Django 3.0 on 2020-04-27 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branch_capital'),
        ('loans', '0014_auto_20200421_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Branch'),
            preserve_default=False,
        ),
    ]
