# Generated by Django 3.0 on 2020-05-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0016_auto_20200504_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
