# Generated by Django 3.1.2 on 2020-11-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0016_auto_20201111_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='interest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=60, null=True),
        ),
    ]
