# Generated by Django 3.0 on 2020-05-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0017_auto_20200506_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
