# Generated by Django 3.1.2 on 2020-11-13 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
        ('loans', '0017_loanrepayment_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='approval_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='first_approval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_approval', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='loan',
            name='second_approval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_approval', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='loan',
            name='staff_permission_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='third_approval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_approval', to='staffs.staff'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='staff_permission_disbursed',
            field=models.BooleanField(default=False),
        ),
    ]
