# Generated by Django 3.0 on 2020-05-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0018_auto_20200507_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
