# Generated by Django 3.1.2 on 2020-11-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0019_auto_20201114_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='leftToBePaidTotal',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='left_to_be_paid',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='outstanding_principal',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='amount_paid',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
