# Generated by Django 3.1.2 on 2020-11-16 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
        ('loans', '0020_auto_20201115_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('loan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='loans.loan')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.staff')),
            ],
        ),
    ]
