# Generated by Django 3.0 on 2020-05-08 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0021_auto_20200508_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancomment',
            name='date',
            field=models.DateField(auto_now=True, default="2020-05-08"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loancomment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.Loan'),
        ),
    ]
