# Generated by Django 3.1.2 on 2020-11-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0021_loanapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanscheduler',
            name='due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='loanscheduler',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='loanscheduler',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='loanscheduler',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='loanscheduler',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='loanscheduler',
            name='pending_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='loanscheduler',
            name='principal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='loanscheduler',
            name='principal_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='loanscheduler',
            name='total_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
