# Generated by Django 3.1.2 on 2020-11-16 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0003_auto_20201109_1048'),
        ('loans', '0022_auto_20201116_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='borrower',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='borrowers.borrower'),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='next_due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='past_due_date',
            field=models.DateField(null=True),
        ),
    ]
