# Generated by Django 3.0 on 2020-05-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0022_auto_20200508_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanscheduler',
            name='date',
            field=models.DateField(),
        ),
    ]
