# Generated by Django 3.1.2 on 2020-11-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0023_auto_20201116_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='last_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
