# Generated by Django 3.0 on 2020-05-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0023_auto_20200508_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_mode',
            field=models.CharField(blank=True, choices=[('Percentage Based', 'Percentage Based'), ('Fixed Amount Per Cycle', 'Fixed Amount Per Cycle')], default='Percentage Based', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='repayment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
