# Generated by Django 3.0 on 2020-05-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0024_auto_20200508_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('open', (('current', 'current'), ('due today', 'due today'), ('missed repayment', 'missed repayment'), ('arrears', 'arrears'), ('past maturity', 'past maturity'))), ('restructured', 'restructured'), ('fully paid', 'fully paid'), ('defaulted', (('credit counselling', 'credit counselling'), ('collection agency', 'collection agency'), ('sequestrate', 'sequestrate'), ('debt review', 'debt review'), ('fraud', 'fraud'), ('investigation', 'investigation'), ('legal', 'legal'), ('write-off', 'write-off'))), ('denied', 'denied'), ('not taken up', 'not taken up')], default='processing', max_length=30),
        ),
    ]
