# Generated by Django 3.0 on 2020-05-08 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0025_auto_20200508_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanofficer',
            name='loan',
        ),
        migrations.CreateModel(
            name='LoanMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Loan')),
                ('loan_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.LoanOfficer')),
            ],
        ),
        migrations.AddField(
            model_name='loanofficer',
            name='members',
            field=models.ManyToManyField(through='loans.LoanMembership', to='loans.Loan'),
        ),
    ]
