# Generated by Django 3.0 on 2020-05-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0026_auto_20200508_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
