# Generated by Django 3.0 on 2020-05-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0027_loan_loan_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='disbursed',
            field=models.BooleanField(default=False),
        ),
    ]
