# Generated by Django 3.0 on 2020-05-08 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0028_loan_disbursed'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandisbursement',
            name='date_disbursed',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='loandisbursement',
            name='loan_officer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='loans.LoanOfficer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loandisbursement',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
