# Generated by Django 3.0 on 2020-05-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    pass

    dependencies = [
        ('loans', '0029_auto_20200508_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_duration',
            field=models.IntegerField(default=0),
        ),
    ]
