# Generated by Django 3.0 on 2020-05-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0031_auto_20200508_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_duration',
            field=models.IntegerField(default=0),
        ),
    ]
