# Generated by Django 3.0 on 2020-05-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0032_auto_20200508_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loandisbursement',
            name='loan_duration',
        ),
    ]
