# Generated by Django 3.0 on 2020-05-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0033_remove_loandisbursement_loan_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loantype',
            old_name='apply_penaly_to',
            new_name='apply_penalty_to',
        ),
    ]
