# Generated by Django 3.0 on 2020-05-08 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0034_auto_20200508_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loantype',
            name='apply_penalty_to',
        ),
    ]
