# Generated by Django 3.0 on 2020-05-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0035_remove_loantype_apply_penalty_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loandisbursement',
            old_name='amount',
            new_name='disbursed_amount',
        ),
        migrations.AddField(
            model_name='loandisbursement',
            name='outstanding',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='loandisbursement',
            name='status',
            field=models.CharField(choices=[('Current', 'Current'), ('Arrears', 'Arrears')], default='Current', max_length=100),
            preserve_default=False,
        ),
    ]
