# Generated by Django 3.0.6 on 2020-05-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0036_auto_20200510_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='total_due_interest',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_due_loan_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_due_penalty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_due_principal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
    ]
