# Generated by Django 3.0.3 on 2020-03-25 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=400)),
                ('middle_name', models.CharField(max_length=400)),
                ('last_name', models.CharField(max_length=400)),
                ('business_name', models.CharField(blank=True, max_length=400, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=100)),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss'), ('Dr.', 'Dr.'), ('Ms.', 'Ms.'), ('Rev', 'Rev')], max_length=100)),
                ('mobile', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100)),
                ('date_of_birth', models.DateTimeField()),
                ('address', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=400)),
                ('state', models.CharField(max_length=400)),
                ('zip_code', models.CharField(max_length=400)),
                ('land_line', models.CharField(max_length=400)),
                ('working_status', models.CharField(choices=[('Employer', 'Employer'), ('Government Employee', 'Government Employee'), ('Private Sector', 'Private Sector'), ('Employee', 'Employee'), ('Owner', 'Owner'), ('Student', 'Student'), ('Overseas Worker', 'Overseas Worker'), ('Pensioner', 'Pensioner'), ('Unemployed', 'Unemployed')], max_length=100)),
                ('borrower_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(max_length=400)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
