# Generated by Django 3.0.3 on 2020-03-25 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('meeting_date', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('group_leader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='borrowers.Borrower')),
            ],
        ),
        migrations.AddField(
            model_name='borrower',
            name='borrower_group',
            field=models.ManyToManyField(to='borrowers.BorrowerGroup'),
        ),
    ]
