# Generated by Django 3.1.2 on 2020-11-04 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='country',
        ),
    ]
