# Generated by Django 3.0.3 on 2020-04-07 08:32

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_esignature'),
        ('borrowers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='user',
        ),
        migrations.AddField(
            model_name='borrower',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrower',
            name='loan_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='borrower_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='date_of_birth',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Ms', 'Ms'), ('Rev', 'Rev')], max_length=100),
        ),
        migrations.CreateModel(
            name='BorrowerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('meeting_date', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('group_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_leader', to='borrowers.Borrower')),
                ('member', models.ManyToManyField(to='borrowers.Borrower')),
            ],
        ),
    ]
