# Generated by Django 3.1.2 on 2020-11-06 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('borrowers', '0001_initial'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='loan_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loanofficer', verbose_name='Loan Officer'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
