# Generated by Django 3.1.2 on 2020-11-04 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('borrowers', '0002_remove_borrower_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.country'),
        ),
    ]
