# Generated by Django 3.0.3 on 2020-03-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0002_auto_20200325_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
