# Generated by Django 3.1.2 on 2020-11-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0002_auto_20201106_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='working_status',
            field=models.CharField(blank=True, choices=[('Employer', 'Employer'), ('Government Employee', 'Government Employee'), ('Private Sector', 'Private Sector'), ('Employee', 'Employee'), ('Owner', 'Owner'), ('Student', 'Student'), ('Overseas Worker', 'Overseas Worker'), ('Pensioner', 'Pensioner'), ('Unemployed', 'Unemployed')], max_length=100),
        ),
    ]
