# Generated by Django 3.0 on 2020-05-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0003_auto_20200420_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='land_line',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='zip_code',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
