# Generated by Django 3.0.3 on 2020-04-01 09:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0003_borrower_is_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='borrower_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
