# Generated by Django 3.1.2 on 2020-11-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0003_auto_20201109_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='inviteborrower',
            name='email_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
