# Generated by Django 3.0.3 on 2020-04-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0004_auto_20200401_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='borrower_group',
            field=models.ManyToManyField(blank=True, null=True, to='borrowers.BorrowerGroup'),
        ),
    ]
