# Generated by Django 3.1.2 on 2020-11-04 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('borrowers', '0004_remove_borrower_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.country'),
        ),
    ]
