# Generated by Django 3.0 on 2020-05-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0004_auto_20200507_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowergroup',
            name='meeting_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
