# Generated by Django 3.0.3 on 2020-04-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0005_auto_20200401_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='date_of_birth',
            field=models.CharField(max_length=400),
        ),
    ]
