# Generated by Django 3.1.2 on 2020-11-06 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_remove_loanofficer_members'),
        ('borrowers', '0005_borrower_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='loan_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loanofficer', verbose_name='Loan Officer'),
        ),
    ]
