# Generated by Django 3.0 on 2020-05-07 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0005_auto_20200507_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowergroup',
            name='member',
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowers.Borrower')),
                ('borrower_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowers.BorrowerGroup')),
            ],
        ),
        migrations.AddField(
            model_name='borrowergroup',
            name='members',
            field=models.ManyToManyField(through='borrowers.Membership', to='borrowers.Borrower'),
        ),
    ]
