# Generated by Django 3.0.3 on 2020-04-03 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_esignature'),
        ('borrowers', '0009_auto_20200402_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='user',
        ),
        migrations.AddField(
            model_name='borrower',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Profile'),
            preserve_default=False,
        ),
    ]
