# Generated by Django 3.0.3 on 2020-04-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0010_auto_20200403_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='profile',
        ),
    ]
