# Generated by Django 3.0.3 on 2020-04-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0010_auto_20200403_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='loan_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Ms', 'Ms'), ('Rev', 'Rev')], max_length=100),
        ),
    ]
