# Generated by Django 3.0.3 on 2020-04-03 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_esignature'),
        ('borrowers', '0013_auto_20200403_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='profile',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
