# Generated by Django 3.0 on 2020-04-23 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branch_capital'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Branch'),
            preserve_default=False,
        ),
    ]
