# Generated by Django 3.0 on 2020-05-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20200502_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='investor_account_commissions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='investor_account_deposits',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='investor_account_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='investor_account_transfer_in',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='investor_account_transfer_out',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='investor_account_withdrawals',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='other_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='savings_commissions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
