# Generated by Django 3.0 on 2020-05-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='message_purpose',
            field=models.CharField(choices=[('to_all_borrowers', 'to_all_borrowers')], max_length=100),
        ),
    ]
