# Generated by Django 3.0.3 on 2020-03-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200327_1135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SendSMS',
            new_name='SMS',
        ),
    ]
